#!/usr/bin/python
import sys, os, re, string, subprocess, shutil, random

def failBuild():
    # Something didn't work. Fail back to compile from scratch.
    if prDebug: sys.stderr.write ("=== Fail Build Attempt ===" +'\n')
    execBuild([clangExec] +  cmdLine.split(), "Fail Build")

def errorCatch(retCode, cmd, mesg):
    if (retCode != 0):
        sys.stderr.write ('========= Error: '+ mesg +' failed\n'+cmd+'\n\n')
        sys.stderr.write( 'os.getcwd(): '+ os.getcwd() +'\n\n')
        sys.stderr.write( 'cmdLine: '+ cmdLine +'\n\n')
        sys.stderr.write( 'outFile: ' + outFile +'\n')
        sys.stderr.write( 'rawFile: ' + rawFile +'\n')
        sys.stderr.write( 'cachedFile: ' + cachedFile +'\n')
    	sys.stderr.write( 'objFile: ' + objFile +'\n')
        sys.stderr.write( 'binFile: ' + binFile +'\n')
        sys.stderr.write( 'bcFile: ' + bcFile +'\n')
        sys.stderr.write( 'blobS: ' + blobS+'\n')
        sys.stderr.write( 'blobSDiv: ' + blobSDiv+'\n')
        #TODO failBuild?
        sys.exit(retCode)
    return retCode

def execBuild(cmd, mesg):
    global retCode
    
    if realBuild:
        process = subprocess.Popen(cmd)
        retCode = process.wait()
    return errorCatch(retCode, string.join(cmd,' '), mesg)


def cacheBitcode(output, inFile):    # Build .bc file if there is no cached version
    if ( not os.path.isfile(output) ):        
        if prDebug: sys.stderr.write ("=== To Bitcode Cache ===" +'\n')
        
        buildBc = cmdLine
        buildBc = re.sub(r'-o\s*\S*\.o',' ', buildBc)
        buildBc = re.sub(r'\W-c\W',r' ', buildBc)
        buildBc = re.sub(r'-i\s*\S*',r' ', buildBc)

	if(inFile is None):
            buildBc = [clangExec, '-o', output, '-S', '-emit-llvm'] + buildBc.split()
        else:
	    buildBc = [clangExec, '-o', output, '-S', '-emit-llvm', inFile]

	#TODO remove un needed flags, -I file, 
        #buildBc = [clangExec, '-o', output, files]
        
        return execBuild(buildBc,"To Bitcode Cache")
    return retCode


def diversify(output, inFile):
    if doDiv:
        if prDebug: sys.stderr.write ("=== Diversify ===" +'\n\n')
        
        #TODO read from command line and purge after use
        seed = str(random.randint(0,100000))
        percent = str(random.randint(0,99))
        
        tests = ""
        
        #tests += "--plugin=/usr/local/lib/MaoSchedRand-x86_64-linux.so:SCHEDRAND=MultiCompilerSeed["+seed+"]+ISchedRandPercentage["+percent+"]:"
        #tests += "--plugin=/usr/local/lib/MaoMOVToLEA-x86_64-linux.so:MOVTOLEA=MultiCompilerSeed["+seed+"]+MOVToLEAPercentage["+percent+"]:"
        tests += "--plugin=/usr/local/lib/MaoNOPInsertion-x86_64-linux.so:NOPINSERTION=MultiCompilerSeed["+seed+"]+NOPInsertionPercentage["+percent+"]:"
        
       # tests += "CFG=respect_orig_labels[1]:"
        #tests += "--plugin=/usr/local/lib/MaoBackBranchAlign-x86_64-linux.so:BACKBRALIGN:"
        #tests += "--plugin=/usr/local/lib/MaoLoop16-x86_64-linux.so:LOOP16:"
        
        
        divBlob = ["mao", "--mao="+tests+"ASM=o["+output+"]", inFile ]
        
        return execBuild(divBlob, "Diversify")
    return retCode


def linkAndCacheAssemblyBlob(output):
    global retCode
    if not os.path.isfile(output):
        if prDebug: sys.stderr.write ("=== Linking Bitcode Files ===" +'\n\n')
        
        inObj = re.findall(r'\S*\.[cCsSo]+[pPxX+]*', cmdLine)
	#For each obj .o located cached .bc file
        #TODO full dir repacement
        for i,item in enumerate(inObj):
	    if item[-2:] == '.o':
                inObj[i] = cacheDir + "/" + re.sub(r'\.o','.bc',item)
	    elif item[-2:] == '.c':
	        #TODO include other source types
	        inObj[i] = cacheDir + "/" + re.sub(r'\.c','.bc',item)
		cacheBitcode(inObj[i], item)

        blobBc = output + ".bc"
        llvmLink = ["llvm-link", "-S", "-o", blobBc] + inObj
        retCode = execBuild(llvmLink, "Linking Bitcode Files") and retCode
        
        if retCode == 0:
	    return cacheAssembly(output, blobBc);
    return retCode

def cacheAssembly(output, inFile):
    if prDebug: sys.stderr.write ("=== Convert Bitcode Blob To Assembly ===" +'\n\n')
    #convert to assembly blob
    #TODO use all cmd line options
    buildFlags = cmdLine

    #remove all .o files replace with blobS
    #TODO other source types
    buildFlags = re.sub(r'\S*\.[co]',' ',buildFlags)
    buildFlags = re.sub(r'-o\s*\S*',' ',buildFlags)
    #TODO isolate -c flag
    buildFlags = re.sub(r'-c',' ',buildFlags)

    assemble = ["clang", "-o", output, "-S", inFile] + string.split(buildFlags," ")

    return execBuild(assemble, "Convert Bitcode Blob To Assembly")



def buildBinFromBlobS(output, inFile):
    if retCode == 0:
        if prDebug: sys.stderr.write ("=== Build Assembly Blob ===" +'\n\n')
        
        flags = cmdLine
        
        #remove all .o files replace with blobSDiv
	#TODO other source types
        flags = re.sub(r'\S*\.[co]',' ',flags)
        flags = re.sub(r'-o\s*\S*',' ',flags)

        buildBin = [clangExec, "-o", output, inFile] + string.split(flags,' ')

        return execBuild(buildBin, "Build Bin From BlobS")
    return retCode

def buildObjectFromBC(output, inFile):
    # Build .o files too.... they are needed...
    if (not os.path.isfile(output) ):
        if prDebug: sys.stderr.write ("=== BC To Object ===" +'\n')

	buildObj=cmdLine
            
	buildObj=re.sub(r'\S*\.[cCsS]+[^o\s]?[pPxX+]*','',buildObj)
	buildObj=re.sub(r'-o[\s]*[\S]*','',buildObj)
        
        buildObj = [clangExec, inFile, '-o', output]+ buildObj.split(' ')
        
        return execBuild(buildObj,"BC To Object")
    return retCode



def main():
    global clangExec
    clangExec = 'clang'
    global retCode
    retCode = 0
    global prDebug
    prDebug=False # output to std err
    global mkdirFlag
    mkdirFlag=True # really make dirs, not just print
    global realBuild
    realBuild=True # really build, not just print
    global doBuildObj
    global doBuildBlob
    global doDiv
    doBuildObj=False
    doBuildBlob=True
    doDiv=True

    # make args a single string
    global cmdLine
    cmdLine = string.join(sys.argv[1:], ' ')
    #TODO pullout flags
    #TODO -buildObject explicit flag

    global outFile
    global rawFile
    global cachedFile
    global cacheDir
    global objFile
    global binFile
    global bcFile
    global blobS
    global blobSDiv
    
    if (sys.argv[1] == "-prDebug"):prDebug = True
    
    #TODO pull seed and percent from commandline 
    #if prDebug: sys.stderr.write( "\n" )
    # Pick the correct clang....
    if ('++' in sys.argv[0]):clangExec = 'clang++'

    # TODO make portable; raw compile configure
    if ( False #bool(re.search(r'workspace/[^/]+/[^/]+\Z',os.getcwd())) # configure fix
    	 or bool(re.search(r'(\A|\s).*\.[sS](\Z|\s)',cmdLine)) # skip .s files for now TODO find way to cache
         or bool(re.search(r'(\A|\s)-E(\Z|\s)',cmdLine)) #Ignore lone preprocessing
         or bool(re.search(r'(\A|\s)conftest\.[ocC]?(\Z|\s)',cmdLine)) #conf exempt
         or bool(re.search(r'/config/?',os.getcwd())) #config folder exempt
         or bool(re.search(r'--version',cmdLine)) #skip version lookups
         or bool(re.search(r'-[vV]',cmdLine)) #skip version lookups
         or bool(re.search(r'-qversion',cmdLine)) #skip version lookups
        ):
	retCode = execBuild([clangExec] + cmdLine.split(), "Excluded Build")
	sys.exit(retCode)

    #TODO cleanup Determine needed files
    # find output file
    outFile = string.join(re.findall(r'-o\s*\S*', cmdLine), ' ')
    
    doFull=False
    if not bool(re.search(r'-o',cmdLine)) :
        doFull=True
        inSrc = re.findall(r'\S*\.[cCsS]+[^o]?[pPxX+]*', cmdLine)
        if len(inSrc) == 1 :
            outFile = re.sub(r'\.[cCsS]+[^o]?[pPxX+]*','.o',os.path.basename(inSrc[0]))
    
    outFile = re.sub(r'-o','',outFile)
    outFile = os.path.realpath(outFile.strip())

    if doFull:
        rawFile = outFile[:-2]
        binFile = rawFile
        objFile = outFile
    if outFile[-2:] == ".o" : #output is an object
        binFile = ""
        objFile = outFile
        rawFile = outFile[:-2]
    #TODO include .so? .exe? .run? ...
    else : #output is a bin... i guess...
        binFile = outFile
        objFile = ''
        rawFile = outFile
    

    # name cached file
    cachedFile = re.sub(r'/home/ubuntu/workspace/','/home/ubuntu/workspace/bcache/',rawFile)
    bcFile = cachedFile + ".bc"
    blobS = cachedFile + ".blob.s"
    blobSDiv = cachedFile + ".blob.div.s"

    # make path to file if needed
    cacheDir = os.path.dirname(cachedFile)
    if cacheDir != '':
        if not os.path.isdir(cacheDir) :
            if mkdirFlag :
                try:
                    os.makedirs(cacheDir)
                except:
                    pass
            else:
                sys.stderr.write ('mkdir file\'s dir: '+cacheDir +'\n')

            
    # There is an .o output file we want to cache
    if len(objFile) != 0:
        # determine location of cached bitcode
        
        cacheBitcode(bcFile,None)
	
	if doBuildObj :
	    cacheAssembly(bcFile+".s", bcFile)
	    diversify(bcFile+"Div.s", bcFile+".s")
            useBc=''
            if doDiv:
                useBc = bcFile+"Div.s"
            else:
                useBc = bcFile+".s"
            buildObjectFromBC(objFile, useBc)
    
    if  len(binFile) != 0:

        #TODO if compiling from .c to bin, do different build
        
        #if input is .c and input.bc doesn't exist; build input.c bitcode
        #if blob doesnt exist; use input.c as .bc

        if doBuildBlob:
            # Build blob object from bitcode
            linkAndCacheAssemblyBlob(blobS)
        
            #Diversify
	    diversify(blobSDiv, blobS)
	    #TODO need better fix, MAO outputs bad alignments(possible fix)
            if(False):
	        f = open(blobSDiv, 'r')
                lines = f.readlines()
	        f.close()
	        f = open(blobSDiv, 'w')
	        for line in lines:
	          if not bool(re.search(r'\.p2align.*, *, *0.*#',line)):
	              f.write(line)
                f.close()

        

            useBlob=''
            if doDiv:
                useBlob = blobSDiv
            else:
                useBlob = blobS

            buildBinFromBlobS(binFile, useBlob)

        else:
	    if prDebug: sys.stderr.write( "buildBinFromObj()\n" )
	    buildBinFromObj()
        

    elif len(outFile) == 0:
        errorCatch(1,'','No Output File')

        
    #if prDebug: sys.stderr.write("ret: "+str(retCode)+ "\n" )
    if prDebug: sys.stderr.write( "\n" )
    sys.exit(retCode)


if __name__ == "__main__":
    main()
