#!/bin/bash
seed=$[ $RANDOM ]
percent=$[ $RANDOM % 100]

loadTests="";runTests=""
loadTests+="--plugin../bin/MaoMOVToLEA-x86_64-linux.so:";runTests+="MOVTOLEA=trace[3]+MultiCompilerSeed[${seed}]+MOVToLEAPercentage[${percent}]:"
loadTests+="--plugin=../bin/MaoNOPInsertion-x86_64-linux.so:";runTests+="NOPINSERTION=trace[3]+MultiCompilerSeed[${seed}]+NOPInsertionPercentage[${percent}]:"
loadTests+="--plugin=../bin/MaoSchedRand-x86_64-linux.so:";runTests+="SCHEDRAND=trace[1]+MultiCompilerSeed[${seed}]+ISchedRandPercentage[${percent}]:"


#../bin/mao-x86_64-linux --mao=--plugin=../bin/MaoNOPInsertion-x86_64-linux.so:--plugin../bin/MaoMOVToLEA-x86_64-linux.so:--plugin=../bin/MaoSchedRand-x86_64-linux.so:${runTests}ASM=o[hellofunc_Div.s] hellofunc.s
../bin/mao-x86_64-linux --mao=${loadTests}${runTests}ASM=o[hellofunc_Div.s] hellofunc.s

gcc -c hellofunc_Div.s -o hellofunc.o
gcc -c hellomake.s -o hellomake.o
gcc hellomake.o hellofunc.o -o hellomake
./hellomake
